allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - "@tanstack/ai-client@0.29.2"
  - "@tanstack/ai-event-client@0.11.2"
  - "@tanstack/ai-solid@0.19.4"
  - "@tanstack/ai@0.52.0"
overrides:
  hono: 4.13.4
