import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const generatedDirectory = join(root, "src", "generated");
const generatedHeader =
  "// Do not edit — generated by `just codegen`.\n// Source: openapi.json.\n";
const clientSource = `${generatedHeader}\nimport createClient, { type ClientOptions } from "openapi-fetch";\n\nimport type { paths } from "./schema";\n\nexport type TetherClient = ReturnType<typeof createTetherClient>;\n\nexport function createTetherClient(options: ClientOptions = {}) {\n  return createClient<paths>({\n    baseUrl: "/",\n    credentials: "include",\n    ...options,\n  });\n}\n`;
const indexSource = `${generatedHeader}\nexport { createTetherClient, type TetherClient } from "./client";\nexport type { components, operations, paths, webhooks } from "./schema";\n`;

await mkdir(generatedDirectory, { recursive: true });
await Promise.all([
  writeFile(join(generatedDirectory, "client.ts"), clientSource),
  writeFile(join(generatedDirectory, "index.ts"), indexSource),
]);
