"""Source-independent Transcript and Transcription interface."""

from tether.transcripts.acquisition import (
    TranscriptAcquisitionConfig,
    TranscriptAcquisitionService,
)
from tether.transcripts.contracts import (
    AsyncClosable,
    FetchedTranscript,
    TranscriptAcquisitionDeferred,
    TranscriptAcquisitionPort,
    TranscriptBlockedFailure,
    TranscriptExplicitlyUnavailable,
    TranscriptFailure,
    TranscriptFetchPolicy,
    TranscriptFetchResult,
    TranscriptionKey,
    TranscriptionTarget,
    TranscriptNeedsReview,
    TranscriptProviderBlocked,
    TranscriptProviderChain,
    TranscriptRequestFailure,
    TranscriptRetryScheduled,
    TranscriptSegment,
    TranscriptSource,
    TranscriptStored,
    TranscriptTransientFailure,
    TranscriptUnavailableFailure,
)
from tether.transcripts.provider_health import load_all_provider_pauses
from tether.transcripts.store import (
    Transcript,
    TranscriptionAvailable,
    TranscriptionRetrying,
    TranscriptionReviewNeeded,
    TranscriptionState,
    TranscriptionStatus,
    TranscriptionStore,
    TranscriptionStoreInvariantError,
    TranscriptionUnavailable,
    create_transcript_schema,
)
from tether.transcripts.supadata import (
    HttpSupadataTransport,
    SupadataConfig,
    SupadataTranscriptSource,
)

__all__ = [
    "AsyncClosable",
    "FetchedTranscript",
    "HttpSupadataTransport",
    "SupadataConfig",
    "SupadataTranscriptSource",
    "Transcript",
    "TranscriptAcquisitionConfig",
    "TranscriptAcquisitionDeferred",
    "TranscriptAcquisitionPort",
    "TranscriptAcquisitionService",
    "TranscriptBlockedFailure",
    "TranscriptExplicitlyUnavailable",
    "TranscriptFailure",
    "TranscriptFetchPolicy",
    "TranscriptFetchResult",
    "TranscriptNeedsReview",
    "TranscriptProviderBlocked",
    "TranscriptProviderChain",
    "TranscriptRequestFailure",
    "TranscriptRetryScheduled",
    "TranscriptSegment",
    "TranscriptSource",
    "TranscriptStored",
    "TranscriptTransientFailure",
    "TranscriptUnavailableFailure",
    "TranscriptionAvailable",
    "TranscriptionKey",
    "TranscriptionRetrying",
    "TranscriptionReviewNeeded",
    "TranscriptionState",
    "TranscriptionStatus",
    "TranscriptionStore",
    "TranscriptionStoreInvariantError",
    "TranscriptionTarget",
    "TranscriptionUnavailable",
    "create_transcript_schema",
    "load_all_provider_pauses",
]
