import { mkdir, readFile, writeFile } from "node:fs/promises";
import { basename, dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const GENERATED_HEADER =
  "// Do not edit — generated by `just codegen`.\n// Source: apps/host/tether/tools.py Pydantic params.\n";

interface JsonSchema {
  $defs?: Record<string, JsonSchema>;
  $ref?: string;
  anyOf?: JsonSchema[];
  default?: unknown;
  description?: string;
  enum?: string[];
  exclusiveMinimum?: number;
  format?: string;
  minLength?: number;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  title?: string;
  type?: string;
}

interface ToolSchema {
  endpoint: string;
  name: string;
  params_model: string;
  schema: JsonSchema;
}

interface ToolSchemaDocument {
  tools: ToolSchema[];
}

function quoted(value: string): string {
  return JSON.stringify(value);
}

function identifierForProperty(name: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : quoted(name);
}

function renderOptions(schema: JsonSchema): string {
  const options: string[] = [];
  if (typeof schema.default !== "undefined") {
    options.push(`default: ${JSON.stringify(schema.default)}`);
  }
  if (typeof schema.exclusiveMinimum === "number") {
    options.push(`exclusiveMinimum: ${String(schema.exclusiveMinimum)}`);
  }
  if (typeof schema.format === "string") {
    options.push(
      `format: ${quoted(schema.format === "uuid7" ? "uuid" : schema.format)}`,
    );
  }
  if (typeof schema.minLength === "number") {
    options.push(`minLength: ${String(schema.minLength)}`);
  }
  return options.length === 0 ? "" : `{ ${options.join(", ")} }`;
}

function renderRequiredExpression(schema: JsonSchema): string {
  if (schema.anyOf !== undefined) {
    // A Pydantic `T | None` field renders as `anyOf: [<T>, null]`; the column
    // is already made `Type.Optional(...)` by being absent from `required`, so
    // only the non-null member needs rendering here.
    const nonNull = schema.anyOf.find((member) => member.type !== "null");
    if (nonNull === undefined) {
      throw new Error(`unsupported schema: ${JSON.stringify(schema)}`);
    }
    return renderRequiredExpression(nonNull);
  }
  if (schema.enum !== undefined) {
    return `StringEnum([${schema.enum.map(quoted).join(", ")}] as const)`;
  }
  const options = renderOptions(schema);
  if (schema.type === "string") {
    return options === "" ? "Type.String()" : `Type.String(${options})`;
  }
  if (schema.type === "integer") {
    return options === "" ? "Type.Integer()" : `Type.Integer(${options})`;
  }
  throw new Error(`unsupported schema: ${JSON.stringify(schema)}`);
}

export function renderTypeBoxProperty(
  name: string,
  schema: JsonSchema,
  required: boolean,
): string {
  const expression = renderRequiredExpression(schema);
  return `${identifierForProperty(name)}: ${required ? expression : `Type.Optional(${expression})`}`;
}

function resolvePropertySchema(
  root: JsonSchema,
  schema: JsonSchema,
): JsonSchema {
  if (schema.$ref === undefined) {
    return schema;
  }
  const prefix = "#/$defs/";
  if (!schema.$ref.startsWith(prefix)) {
    throw new Error(`unsupported $ref: ${schema.$ref}`);
  }
  const name = schema.$ref.slice(prefix.length);
  const resolved = root.$defs?.[name];
  if (resolved === undefined) {
    throw new Error(`unresolved $ref: ${schema.$ref}`);
  }
  return resolved;
}

function renderParameters(tool: ToolSchema): string {
  const properties = tool.schema.properties ?? {};
  const required = new Set(tool.schema.required ?? []);
  const rendered = Object.entries(properties).map(([name, schema]) =>
    renderTypeBoxProperty(
      name,
      resolvePropertySchema(tool.schema, schema),
      required.has(name),
    ),
  );
  return `Type.Object({\n${rendered.map((line) => `  ${line},`).join("\n")}\n})`;
}

function pascalCase(value: string): string {
  return value
    .split("_")
    .map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`)
    .join("");
}

function sentenceForTool(tool: ToolSchema): string {
  return tool.schema.description ?? `${tool.name} Memory tool.`;
}

function usesStringEnum(tool: ToolSchema): boolean {
  return Object.values(tool.schema.properties ?? {}).some((schema) => {
    const resolved = resolvePropertySchema(tool.schema, schema);
    return resolved.enum !== undefined;
  });
}

function renderToolFile(tool: ToolSchema): string {
  const typeName = tool.params_model;
  const variablePrefix = tool.name;
  const registrationName = `register${pascalCase(tool.name)}Tool`;
  const imports = [
    'import type { ExtensionAPI, ToolDefinition } from "@earendil-works/pi-coding-agent";',
    usesStringEnum(tool)
      ? 'import { StringEnum } from "@earendil-works/pi-ai";'
      : undefined,
    'import { Type, type Static } from "typebox";',
    'import { executeTetherTool, type TetherToolDetails } from "../runtime.js";',
  ].filter((line) => line !== undefined);

  return `${GENERATED_HEADER}\n${imports.join("\n")}\n\nconst ${variablePrefix}Parameters = ${renderParameters(tool)};\n\nexport type ${typeName} = Static<typeof ${variablePrefix}Parameters>;\n\nexport const ${variablePrefix}Tool: ToolDefinition<typeof ${variablePrefix}Parameters, TetherToolDetails> = {\n  name: ${quoted(tool.name)},\n  label: ${quoted(pascalCase(tool.name))},\n  description: ${quoted(sentenceForTool(tool))},\n  promptSnippet: ${quoted(sentenceForTool(tool))},\n  parameters: ${variablePrefix}Parameters,\n  async execute(_toolCallId, params, signal) {\n    return executeTetherTool(\n      { endpoint: ${quoted(tool.endpoint)}, name: ${quoted(tool.name)} },\n      params,\n      signal,\n    );\n  },\n};\n\nexport function ${registrationName}(pi: ExtensionAPI): void {\n  pi.registerTool(${variablePrefix}Tool);\n}\n\nexport default function ${variablePrefix}ToolExtension(pi: ExtensionAPI): void {\n  ${registrationName}(pi);\n}\n`;
}

function renderIndexFile(tools: ToolSchema[]): string {
  const imports = tools.map(
    (tool) =>
      `import { register${pascalCase(tool.name)}Tool } from "./${tool.name}.js";`,
  );
  const registrations = tools.map(
    (tool) => `  register${pascalCase(tool.name)}Tool(pi);`,
  );
  return `${GENERATED_HEADER}\nimport type { ExtensionAPI } from "@earendil-works/pi-coding-agent";\n${imports.join("\n")}\n\nexport default function tetherToolsExtension(pi: ExtensionAPI): void {\n${registrations.join("\n")}\n}\n`;
}

async function readSchemaDocument(path: string): Promise<ToolSchemaDocument> {
  return JSON.parse(await readFile(path, "utf8")) as ToolSchemaDocument;
}

async function writeGeneratedFiles(
  document: ToolSchemaDocument,
  outputDir: string,
): Promise<void> {
  await mkdir(outputDir, { recursive: true });
  await Promise.all([
    ...document.tools.map((tool) =>
      writeFile(join(outputDir, `${tool.name}.ts`), renderToolFile(tool)),
    ),
    writeFile(join(outputDir, "index.ts"), renderIndexFile(document.tools)),
  ]);
}

export async function generateToolShims(
  schemaPath = join(
    dirname(dirname(fileURLToPath(import.meta.url))),
    "generated",
    "tool-schemas.json",
  ),
  outputDir = join(
    dirname(dirname(fileURLToPath(import.meta.url))),
    "src",
    "generated",
  ),
): Promise<void> {
  await writeGeneratedFiles(await readSchemaDocument(schemaPath), outputDir);
}

if (pathToFileURL(process.argv[1] ?? "").href === import.meta.url) {
  generateToolShims().catch((error: unknown) => {
    const scriptName = basename(fileURLToPath(import.meta.url));
    console.error(
      `${scriptName}: ${error instanceof Error ? error.message : String(error)}`,
    );
    process.exitCode = 1;
  });
}
