import pyarrow as pa
from lancedb.table import AsyncTable

class ListTablesResponse:
    tables: list[str]

class AsyncConnection:
    async def list_tables(self) -> ListTablesResponse: ...
    async def open_table(self, name: str) -> AsyncTable: ...
    async def create_table(self, name: str, *, schema: pa.Schema) -> AsyncTable: ...
    async def drop_table(self, name: str) -> None: ...
