from typing import Any

from lancedb.rerankers import RRFReranker

class AsyncHybridQuery:
    def rerank(self, reranker: RRFReranker) -> AsyncHybridQuery: ...
    def limit(self, limit: int) -> AsyncHybridQuery: ...
    async def to_list(self) -> list[dict[str, Any]]: ...

class AsyncVectorQuery:
    def nearest_to_text(self, text: str) -> AsyncHybridQuery: ...

class AsyncQuery:
    def nearest_to(self, vector: list[float]) -> AsyncVectorQuery: ...
    def select(self, columns: list[str]) -> AsyncQuery: ...
    async def to_list(self) -> list[dict[str, Any]]: ...
