from collections.abc import Iterable, Mapping
from typing import Any

import pyarrow as pa
from lancedb.index import FTS
from lancedb.query import AsyncQuery

class LanceMergeInsertBuilder:
    def when_matched_update_all(self) -> LanceMergeInsertBuilder: ...
    def when_not_matched_insert_all(self) -> LanceMergeInsertBuilder: ...
    async def execute(self, new_data: Iterable[Mapping[str, Any]]) -> Any: ...

class AsyncTable:
    async def schema(self) -> pa.Schema: ...
    async def create_index(self, column: str, *, config: FTS) -> None: ...
    def merge_insert(self, on: str) -> LanceMergeInsertBuilder: ...
    async def delete(self, where: str) -> None: ...
    async def count_rows(self) -> int: ...
    async def optimize(self) -> Any: ...
    def query(self) -> AsyncQuery: ...
